/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udistrital.estudiantes.simulatorspa;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;

/**
 *
 * @author jhogarcia
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private javax.swing.JButton jButton1;
    private IComponentsSimulator PC;
    private IComponentsSimulator MAR;
    private IComponentsSimulator RAM;
    private IComponentsSimulator IR;
    private IComponentsSimulator UC;
    private IComponentsSimulator AC;
    private IComponentsSimulator ALU;
    private IComponentsSimulator B;
    private IComponentsSimulator OUT;
    private IComponentsSimulator RESULT;
    

 
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setSize( 800, 800 );
        setVisible( true );
        ComponentsFactory componentsFactory = new ComponentsFactory();
        PC = componentsFactory.getComponent("PC");
        MAR = componentsFactory.getComponent("MAR");
        RAM = componentsFactory.getComponent("RAM");
        IR= componentsFactory.getComponent("IR");
        UC= componentsFactory.getComponent("UC");
        AC = componentsFactory.getComponent("AC");
        ALU = componentsFactory.getComponent("ALU");
        B = componentsFactory.getComponent("B");
        OUT = componentsFactory.getComponent("OUT");
        RESULT = componentsFactory.getComponent("RESULT");
    }

    
   
    
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        pintarBase(g);
        
   
//      paintComponents(g);
 
    }

    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g); //To change body of generated methods, choose Tools | Templates.
     
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        RAM.setEstadoLineasIn(!RAM.getEstadoLineasIn());
        repaint();
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    public void pintarBase(Graphics g){
        
        buildBUS(g);
        buildPC(g,PC);
        buildMAR(g,MAR);
        buildRAM(g,RAM);
//        buildIR(g,IR);
        buildUC(g,UC);
        buildAC(g,AC);
        buildALU(g,ALU);
        buildB(g,B);
        buildOUT(g,OUT);
        buildResult(g,RESULT);
    }
    
    public void buildLinesLeftBoardOUT(int xi, int xf, Graphics g, IComponentsSimulator component){
        //OuT LINE
        if(component.getEstadoLineasOut()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        for(int i = xi+5; i <= xf-5;i = i+5){
            g.drawLine( 140, i, 230, i );
        }
        // ARROW OUT
        int middle = (xi+xf)/2;
        g.drawLine( 190, xi, 205, middle );
        g.drawLine( 190, xf, 205, middle );
    }
    
    public void buildLinesLeftBoardIN(int xi, int xf, Graphics g, IComponentsSimulator component){
        //OuT LINE
        if(component.getEstadoLineasIn()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        for(int i = xi+5; i <= xf-5;i = i+5){
            g.drawLine( 140, i, 230, i );
        }
        // ARROW OUT
        int middle = (xi+xf)/2;
        g.drawLine( 155, middle, 170, xi );
        g.drawLine( 155, middle, 170, xf );
    }
    
    
    public void buildLinesRightBoardOUT(int xi, int xf, Graphics g, IComponentsSimulator component){
        //OuT LINE
        for(int i = xi+5; i <= xf-5;i = i+5){
            g.drawLine( 310, i, 380, i );
        }
        // ARROW OUT
        int middle = (xi+xf)/2;
        g.drawLine( 320, middle, 335, xi );
        g.drawLine( 320, middle, 335, xf );
    }
    
    public void buildLinesRightBoardIN(int xi, int xf, Graphics g, IComponentsSimulator component){
        //OuT LINE
        for(int i = xi+5; i <= xf-5;i = i+5){
            g.drawLine( 310, i, 380, i );
        }
        // ARROW OUT
        int middle = (xi+xf)/2;
        g.drawLine( 350, xi, 365, middle );
        g.drawLine( 350, xf, 365, middle );
    }
    
    
     // Begin center board
    public void buildBUS(Graphics g){
        g.drawString( "0", 310, 60);
        g.drawLine(310, 60, 310, 480 );
        
        g.drawString( "1", 300, 60);
        g.drawLine(300, 60, 300, 480 );
        
        g.drawString( "2", 290, 60);
        g.drawLine(290, 60, 290, 480 );
        
        g.drawString( "3", 280, 60);
        g.drawLine(280, 60, 280, 480 );
        
        g.drawString( "4", 270, 60);
        g.drawLine(270, 60, 270, 480 );
        
        g.drawString( "5", 260, 60);
        g.drawLine(260, 60, 260, 480 );
        
        g.drawString( "6", 250, 60);
        g.drawLine(250, 60, 250, 480 );
        
        g.drawString( "7", 240, 60);
        g.drawLine(240, 60, 240, 480 );
    };
    // End Center board
    
    // Begin left board
    public void buildPC(Graphics g, IComponentsSimulator component){
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawString( "PC", 20, 60 );
        g.drawRect( 20, 60, 120, 60 );
        
        buildLinesLeftBoardOUT(60,90,g,component);
        buildLinesLeftBoardIN(90,120,g,component);
    };
    
    public void buildMAR(Graphics g, IComponentsSimulator component){
        g.drawString("MAR", 20, 140);
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 20, 140, 120, 60 );
        
        buildLinesLeftBoardOUT(140,170,g,component);
        buildLinesLeftBoardIN(170,200,g,component);
        
    };
    
    public void buildRAM(Graphics g, IComponentsSimulator component){
        //RAM
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawString( component.getNombre(), 20, 220 );
        g.drawRect( 20, 220, 120, 60 );
        
        buildLinesLeftBoardOUT(220,250,g,component);
        buildLinesLeftBoardIN(250,280,g,component);
    };
    
    public void buildIR(Graphics g, IComponentsSimulator component){
         //RI
        g.drawString( "REG. INST.", 40, 300 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 20, 300, 120, 60 );
        buildLinesLeftBoardOUT(300,330,g,component);
        buildLinesLeftBoardIN(330,360,g,component);
    };
    
    public void buildUC(Graphics g, IComponentsSimulator component){
         //CS
        g.drawString( "UC", 20, 380 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 20, 380, 120, 60 );
        buildLinesLeftBoardOUT(380,410,g,component);
        buildLinesLeftBoardIN(410,440,g,component);
    };
    // End left board
    
    // Begin Rigth board
    public void buildAC(Graphics g, IComponentsSimulator component){
        //A
        g.drawString( "A", 380, 60 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect(380, 60, 120, 60 );
        
        buildLinesRightBoardOUT(60,90,g,component);
        buildLinesRightBoardIN(90,120,g,component);
    };
    
    public void buildALU(Graphics g, IComponentsSimulator component){
        //ALU
        g.drawString( "ALU", 380, 140 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 380, 140, 120, 60 );
        
        buildLinesRightBoardOUT(140,170,g,component);
        buildLinesRightBoardIN(170,200,g,component);
    };
    
    public void buildB(Graphics g, IComponentsSimulator component){
        //B
        g.drawString( "B", 380, 220 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 380, 220, 120, 60 );
        
        buildLinesRightBoardOUT(220,250,g,component);
        buildLinesRightBoardIN(250,280,g,component);
    };
    
    public void buildOUT(Graphics g, IComponentsSimulator component){
        //RS
        g.drawString( "RS", 380, 300 );
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 380, 300, 120, 60 );
        
        buildLinesRightBoardOUT(300,330,g,component);
        buildLinesRightBoardIN(330,360,g,component);
    };
    
    public void buildResult(Graphics g, IComponentsSimulator component){
         //DISPLAY
        g.drawString( "DISPLAY", 380, 380);
        if(component.getEstado()){
            g.setColor(Color.red);
        }else {
            g.setColor(Color.black);
        }
        g.drawRect( 380, 380, 120, 60 );
        
        buildLinesRightBoardOUT(380,410,g,component);
        buildLinesRightBoardIN(410,440,g,component);
    };
    // End Rigth board
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
